local types = {id="string", desc_cn="string", desc_en="string"}
local table = {
[login01]={id="login01",desc_cn="登录",desc_en="Login"},
[Loading01]={id="Loading01",desc_cn="场景加载中....",desc_en="Scene loading...."},
[SkillChooseTitle]={id="SkillChooseTitle",desc_cn="武器选择",desc_en="LV UP"},
[SkillChooseTips]={id="SkillChooseTips",desc_cn="选择一个新的武器",desc_en="CHOOSE A NEW WEAPON"},
[HallText0]={id="HallText0",desc_cn="BATTLE",desc_en="BATTLE"},
[HallText1]={id="HallText1",desc_cn="LV UP",desc_en="LV UP"},
[HallText2]={id="HallText2",desc_cn="TTACK",desc_en="TTACK"},
[HallText3]={id="HallText3",desc_cn="HIELD",desc_en="HIELD"},
[HallText4]={id="HallText4",desc_cn="PEED",desc_en="PEED"},
[HallText5]={id="HallText5",desc_cn="ANGE",desc_en="ANGE"},
[HallText6]={id="HallText6",desc_cn="OBILITY",desc_en="OBILITY"},
[HallText7]={id="HallText7",desc_cn="<size=24>x</size>%d",desc_en="<size=24>x</size>%d"},
[HallText8]={id="HallText8",desc_cn="Max",desc_en="Max"},
[HallText9]={id="HallText9",desc_cn="UNLOCK",desc_en="UNLOCK"},
[HallText10]={id="HallText10",desc_cn="Lv.",desc_en="Lv."},
[HallText11]={id="HallText11",desc_cn="MAP",desc_en="MAP"},
[HallText12]={id="HallText12",desc_cn="TYPES",desc_en="TYPES"},
[HallText13]={id="HallText13",desc_cn="A",desc_en="A"},
[HallText14]={id="HallText14",desc_cn="S",desc_en="S"},
[HallText15]={id="HallText15",desc_cn="S",desc_en="S"},
[HallText16]={id="HallText16",desc_cn="R",desc_en="R"},
[HallText17]={id="HallText17",desc_cn="M",desc_en="M"},
[HallText18]={id="HallText18",desc_cn="TTACK",desc_en="TTACK"},
[HallText19]={id="HallText19",desc_cn="HIELD",desc_en="HIELD"},
[HallText20]={id="HallText20",desc_cn="PEED",desc_en="PEED"},
[HallText21]={id="HallText21",desc_cn="ANGE",desc_en="ANGE"},
[HallText22]={id="HallText22",desc_cn="OBILITY",desc_en="OBILITY"},
[HallText23]={id="HallText23",desc_cn="ENDLESS",desc_en="ENDLESS"},
[BtleText01]={id="BtleText01",desc_cn="RESULT",desc_en="RESULT"},
[BtleText02]={id="BtleText02",desc_cn="KILL COUNT",desc_en="KILL COUNT"},
[BtleText03]={id="BtleText03",desc_cn="GET POINTS",desc_en="GET POINTS"},
[BtleText04]={id="BtleText04",desc_cn="BACK",desc_en="BACK"},
[BtleText05]={id="BtleText05",desc_cn="x2",desc_en="x2"},
[BtleText06]={id="BtleText06",desc_cn="复活",desc_en="REVIVE"},
[BtleText07]={id="BtleText07",desc_cn="EXEMPTION",desc_en="EXEMPTION"},
[BtleText08]={id="BtleText08",desc_cn="观看激励视频可以获得双倍奖励",desc_en="WATCH THE VIDEO TO REWARD X2"},
[TipsText0]={id="TipsText0",desc_cn="Tips",desc_en="Tips"},
[TipsText1]={id="TipsText1",desc_cn="恭喜获得",desc_en="Congratulations"},
[TipsText2]={id="TipsText2",desc_cn="<size=36>x</size>%d",desc_en="<size=36>x</size>%d"},
[TipsText3]={id="TipsText3",desc_cn="等待中...",desc_en="Waiting for other players..."},
[TipsText4]={id="TipsText4",desc_cn="包含贵重道具，是否出售？",desc_en="Contains valuable items. Are they for sale?"},
[TipsText5]={id="TipsText5",desc_cn="ATTACK",desc_en="ATTACK"},
[TipsText6]={id="TipsText6",desc_cn="SPEED",desc_en="SPEED"},
[TipsText7]={id="TipsText7",desc_cn="RANGE",desc_en="RANGE"},
[AgreementTitile]={id="AgreementTitile",desc_cn="用户协议",desc_en="Agreements"},
[Agreement1]={id="Agreement1",desc_cn="隐私权政策",desc_en="Privacy Policy"},
[Agreement2]={id="Agreement2",desc_cn="使用者协议",desc_en="User Agreement"},
[SettingTitle]={id="SettingTitle",desc_cn="SETTINGS",desc_en="SETTINGS"},
[SettingText1]={id="SettingText1",desc_cn="音乐",desc_en="BGM"},
[SettingText2]={id="SettingText2",desc_cn="音效",desc_en="SE"},
[SettingText3]={id="SettingText3",desc_cn="语言",desc_en="LANGUAGE"},
[SettingText4]={id="SettingText4",desc_cn="隐私权政策",desc_en="Privacy Policy"},
[SettingText5]={id="SettingText5",desc_cn="用户协议",desc_en="User Agreement"},
[GMText02]={id="GMText02",desc_cn="参数(多个参数使用空格隔开)：%s",desc_en="参数(多个参数使用空格隔开)：%s"},
[GMText03]={id="GMText03",desc_cn="请输入参数…",desc_en="请输入参数…"},
[SysTem01]={id="SysTem01",desc_cn="确认",desc_en="确认"},
[SysTem02]={id="SysTem02",desc_cn="取消",desc_en="取消"},
[SysTem03]={id="SysTem03",desc_cn="提示",desc_en="提示"},
[MatchText01]={id="MatchText01",desc_cn="匹配",desc_en="MATCHING"},
[SpinText1]={id="SpinText1",desc_cn="test",desc_en="test"},
[SpinText2]={id="SpinText2",desc_cn="test",desc_en="test"},
[SpinText3]={id="SpinText3",desc_cn="test",desc_en="test"},
[SpinText4]={id="SpinText4",desc_cn="test",desc_en="test"},
[SpinText5]={id="SpinText5",desc_cn="test",desc_en="test"},
[SpinText6]={id="SpinText6",desc_cn="test",desc_en="test"},
[Free1]={id="Free1",desc_cn="免费",desc_en="Free"},
[SkillName1]={id="SkillName1",desc_cn="技能名字",desc_en="技能名字"},
[S1000]={id="S1000",desc_cn="机炮",desc_en="RailGun"},
[S1100]={id="S1100",desc_cn="导弹",desc_en="Missile"},
[S1200]={id="S1200",desc_cn="导弹（齐射）",desc_en="Area Missile"},
[S1300]={id="S1300",desc_cn="霰弹",desc_en="ShotGun"},
[S1400]={id="S1400",desc_cn="激光",desc_en="Laser"},
[S1500]={id="S1500",desc_cn="激光（ALL）",desc_en="Area Laser"},
[S1600]={id="S1600",desc_cn="尾部导弹",desc_en="Tail Missile"},
[S1700]={id="S1700",desc_cn="尾部导弹",desc_en="Tail Laser"},
[S1800]={id="S1800",desc_cn="重机炮",desc_en="Juke Gun"},
[S1900]={id="S1900",desc_cn="字母导弹",desc_en="Letter Missile"},
[S2000]={id="S2000",desc_cn="扩散激光",desc_en="Dispersion Laser"},
[S2100]={id="S2100",desc_cn="反射激光",desc_en="Reflection Laser"},
[S2200]={id="S2200",desc_cn="浮游机雷",desc_en="Arial Ray"},
[S2300]={id="S2300",desc_cn="尾翼机雷",desc_en="Tail Ray"},
[H1]={id="H1",desc_cn="闪电",desc_en="THUNDER-I"},
[H2]={id="H2",desc_cn="流风",desc_en="JUDGEMENT"},
[H3]={id="H3",desc_cn="火蝙",desc_en="OBERON"},
[H4]={id="H4",desc_cn="海胆",desc_en="MANTIX"},
[H5]={id="H5",desc_cn="烈焰",desc_en="VALORA"},
[H6]={id="H6",desc_cn="眼镜蛇",desc_en="SWIFT JAMMER"},
[H7]={id="H7",desc_cn="法玛斯",desc_en="RAPTOR FLARE"},
[H8]={id="H8",desc_cn="法玛斯",desc_en="TYRANT CLASS I"},
[H9]={id="H9",desc_cn="法玛斯",desc_en="RAZOR"},
[H10]={id="H10",desc_cn="法玛斯",desc_en="EXHIL"},
[H11]={id="H11",desc_cn="法玛斯",desc_en="MAGMA CORE"},
[H5000]={id="H5000",desc_cn="飞机1",desc_en="GX782"},
[H5100]={id="H5100",desc_cn="飞机2",desc_en="YF-01S"},
[H5200]={id="H5200",desc_cn="飞机3",desc_en="XY-MKII"},
[H5300]={id="H5300",desc_cn="飞机4",desc_en="NT-2"},
[E10]={id="E10",desc_cn="MINIGUN LV1",desc_en="MINIGUN LV1"},
[E11]={id="E11",desc_cn="MINIGUN LV2",desc_en="MINIGUN LV2"},
[E12]={id="E12",desc_cn="MINIGUN LV3",desc_en="MINIGUN LV3"},
[E13]={id="E13",desc_cn="MINIGUN LV4",desc_en="MINIGUN LV4"},
[E14]={id="E14",desc_cn="MINIGUN LV5",desc_en="MINIGUN LV5"},
[E15]={id="E15",desc_cn="DOUBLE MINIGUN lv1",desc_en="DOUBLE MINIGUN lv1"},
[E16]={id="E16",desc_cn="DOUBLE MINIGUN lv2",desc_en="DOUBLE MINIGUN lv2"},
[E17]={id="E17",desc_cn="DOUBLE MINIGUN lv3",desc_en="DOUBLE MINIGUN lv3"},
[E18]={id="E18",desc_cn="DOUBLE MINIGUN lv4",desc_en="DOUBLE MINIGUN lv4"},
[E19]={id="E19",desc_cn="DOUBLE MINIGUN lv5",desc_en="DOUBLE MINIGUN lv5"},
[E20]={id="E20",desc_cn="LASER LV1",desc_en="LASER LV1"},
[E21]={id="E21",desc_cn="LASER LV2",desc_en="LASER LV2"},
[E22]={id="E22",desc_cn="LASER LV3",desc_en="LASER LV3"},
[E23]={id="E23",desc_cn="LASER LV4",desc_en="LASER LV4"},
[E24]={id="E24",desc_cn="LASER LV5",desc_en="LASER LV5"},
[E25]={id="E25",desc_cn="DOUBLE LASER lv1",desc_en="DOUBLE LASER lv1"},
[E26]={id="E26",desc_cn="DOUBLE LASER lv2",desc_en="DOUBLE LASER lv2"},
[E27]={id="E27",desc_cn="DOUBLE LASER lv3",desc_en="DOUBLE LASER lv3"},
[E28]={id="E28",desc_cn="DOUBLE LASER lv4",desc_en="DOUBLE LASER lv4"},
[E29]={id="E29",desc_cn="DOUBLE LASER lv5",desc_en="DOUBLE LASER lv5"},
[E30]={id="E30",desc_cn="MISSILE LV1",desc_en="MISSILE LV1"},
[E31]={id="E31",desc_cn="MISSILE LV2",desc_en="MISSILE LV2"},
[E32]={id="E32",desc_cn="MISSILE LV3",desc_en="MISSILE LV3"},
[E33]={id="E33",desc_cn="MISSILE LV4",desc_en="MISSILE LV4"},
[E34]={id="E34",desc_cn="MISSILE LV5",desc_en="MISSILE LV5"},
[E35]={id="E35",desc_cn="DOUBLE MISSILE lv1",desc_en="DOUBLE MISSILE lv1"},
[E36]={id="E36",desc_cn="DOUBLE MISSILE lv2",desc_en="DOUBLE MISSILE lv2"},
[E37]={id="E37",desc_cn="DOUBLE MISSILE lv3",desc_en="DOUBLE MISSILE lv3"},
[E38]={id="E38",desc_cn="DOUBLE MISSILE lv4",desc_en="DOUBLE MISSILE lv4"},
[E39]={id="E39",desc_cn="DOUBLE MISSILE lv5",desc_en="DOUBLE MISSILE lv5"},
[E40]={id="E40",desc_cn="WING PLAN LV1",desc_en="WING PLAN LV1"},
[E41]={id="E41",desc_cn="WING PLAN LV2",desc_en="WING PLAN LV2"},
[E42]={id="E42",desc_cn="WING PLAN LV3",desc_en="WING PLAN LV3"},
[E43]={id="E43",desc_cn="WING PLAN LV4",desc_en="WING PLAN LV4"},
[E44]={id="E44",desc_cn="WING PLAN LV5",desc_en="WING PLAN LV5"},
[E45]={id="E45",desc_cn="2 WING PLAN LV1",desc_en="2 WING PLAN LV1"},
[E46]={id="E46",desc_cn="2 WING PLAN LV2",desc_en="2 WING PLAN LV2"},
[E47]={id="E47",desc_cn="2 WING PLAN LV3",desc_en="2 WING PLAN LV3"},
[E48]={id="E48",desc_cn="2 WING PLAN LV4",desc_en="2 WING PLAN LV4"},
[E49]={id="E49",desc_cn="2 WING PLAN LV5",desc_en="2 WING PLAN LV5"},
[TIPS10]={id="TIPS10",desc_cn="Keep up the attack on the enemy in front",desc_en="Keep up the attack on the enemy in front"},
[TIPS11]={id="TIPS11",desc_cn="Keep up the attack on the enemy in front",desc_en="Keep up the attack on the enemy in front"},
[TIPS12]={id="TIPS12",desc_cn="Keep up the attack on the enemy in front",desc_en="Keep up the attack on the enemy in front"},
[TIPS13]={id="TIPS13",desc_cn="Keep up the attack on the enemy in front",desc_en="Keep up the attack on the enemy in front"},
[TIPS14]={id="TIPS14",desc_cn="Keep up the attack on the enemy in front",desc_en="Keep up the attack on the enemy in front"},
[TIPS15]={id="TIPS15",desc_cn="Keep up the attack on the enemy in front,More firepower",desc_en="Keep up the attack on the enemy in front,More firepower"},
[TIPS16]={id="TIPS16",desc_cn="Keep up the attack on the enemy in front,More firepower",desc_en="Keep up the attack on the enemy in front,More firepower"},
[TIPS17]={id="TIPS17",desc_cn="Keep up the attack on the enemy in front,More firepower",desc_en="Keep up the attack on the enemy in front,More firepower"},
[TIPS18]={id="TIPS18",desc_cn="Keep up the attack on the enemy in front,More firepower",desc_en="Keep up the attack on the enemy in front,More firepower"},
[TIPS19]={id="TIPS19",desc_cn="Keep up the attack on the enemy in front,More firepower",desc_en="Keep up the attack on the enemy in front,More firepower"},
[TIPS20]={id="TIPS20",desc_cn="Shoot a laser at the enemy in front",desc_en="Shoot a laser at the enemy in front"},
[TIPS21]={id="TIPS21",desc_cn="Shoot a laser at the enemy in front",desc_en="Shoot a laser at the enemy in front"},
[TIPS22]={id="TIPS22",desc_cn="Shoot a laser at the enemy in front",desc_en="Shoot a laser at the enemy in front"},
[TIPS23]={id="TIPS23",desc_cn="Shoot a laser at the enemy in front",desc_en="Shoot a laser at the enemy in front"},
[TIPS24]={id="TIPS24",desc_cn="Shoot a laser at the enemy in front",desc_en="Shoot a laser at the enemy in front"},
[TIPS25]={id="TIPS25",desc_cn="Shoot more laser at the enemy in front",desc_en="Shoot more laser at the enemy in front"},
[TIPS26]={id="TIPS26",desc_cn="Shoot more laser at the enemy in front",desc_en="Shoot more laser at the enemy in front"},
[TIPS27]={id="TIPS27",desc_cn="Shoot more laser at the enemy in front",desc_en="Shoot more laser at the enemy in front"},
[TIPS28]={id="TIPS28",desc_cn="Shoot more laser at the enemy in front",desc_en="Shoot more laser at the enemy in front"},
[TIPS29]={id="TIPS29",desc_cn="Shoot more laser at the enemy in front",desc_en="Shoot more laser at the enemy in front"},
[TIPS30]={id="TIPS30",desc_cn="missile will continue to track the target over a certain distance",desc_en="missile will continue to track the target over a certain distance"},
[TIPS31]={id="TIPS31",desc_cn="missile will continue to track the target over a certain distance",desc_en="missile will continue to track the target over a certain distance"},
[TIPS32]={id="TIPS32",desc_cn="missile will continue to track the target over a certain distance",desc_en="missile will continue to track the target over a certain distance"},
[TIPS33]={id="TIPS33",desc_cn="missile will continue to track the target over a certain distance",desc_en="missile will continue to track the target over a certain distance"},
[TIPS34]={id="TIPS34",desc_cn="missile will continue to track the target over a certain distance",desc_en="missile will continue to track the target over a certain distance"},
[TIPS35]={id="TIPS35",desc_cn="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance",desc_en="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance"},
[TIPS36]={id="TIPS36",desc_cn="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance",desc_en="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance"},
[TIPS37]={id="TIPS37",desc_cn="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance",desc_en="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance"},
[TIPS38]={id="TIPS38",desc_cn="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance",desc_en="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance"},
[TIPS39]={id="TIPS39",desc_cn="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance",desc_en="Fire multiple missiles at the enemy at once,missile will continue to track the target over a certain distance"},
[TIPS40]={id="TIPS40",desc_cn="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time",desc_en="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time"},
[TIPS41]={id="TIPS41",desc_cn="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time",desc_en="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time"},
[TIPS42]={id="TIPS42",desc_cn="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time",desc_en="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time"},
[TIPS43]={id="TIPS43",desc_cn="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time",desc_en="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time"},
[TIPS44]={id="TIPS44",desc_cn="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time",desc_en="The concubine will attack enemies within a certain range autonomously.If destroyed, it will respawn after a certain amount of time"},
[TIPS45]={id="TIPS45",desc_cn="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate",desc_en="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate"},
[TIPS46]={id="TIPS46",desc_cn="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate",desc_en="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate"},
[TIPS47]={id="TIPS47",desc_cn="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate",desc_en="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate"},
[TIPS48]={id="TIPS48",desc_cn="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate",desc_en="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate"},
[TIPS49]={id="TIPS49",desc_cn="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate",desc_en="Can resist the trajectory of the bullet attack, can not block area damage, after a certain amount of time after damage can regenerate"}
}
return {table, types}